/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import database.Hirachy;
import java.sql.ResultSet;
import java.sql.SQLException;
import factura.Factura;
import java.awt.Dimension;
import persona.Vendedor;
import vehiculo.VehiculoInterface;

/**
 *
 * @author juansa6201
 */
public class FacturaUI extends javax.swing.JFrame {

    private final VehiculoInterface vehiculo;
    private final Factura factura;
    private Vendedor vendedor;

    /**
     * Creates new form Factura
     *
     * @param vehiculo
     * @param factura
     */
    public FacturaUI(VehiculoInterface vehiculo, Factura factura) {
        initComponents();
        this.setSize(new Dimension(1280, 720));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Factura");
        this.vehiculo = vehiculo;
        this.factura = factura;
        Hirachy hierachy = new Hirachy();
        getVendedor(hierachy);
        setLabels();
    }

    // Obtenemos el vendedor requerido.
    private void getVendedor(Hirachy hierachy) {
        try {
            ResultSet vendedor = hierachy.getVendedor(this.factura.getIdVendedor());
            while (vendedor.next()) {
                Integer id = vendedor.getInt("idVendedor");
                String nombre = vendedor.getString("nombre");
                String apellido = vendedor.getString("apellido");
                String dni = vendedor.getString("dni");
                String legajo = vendedor.getString("legajo");
                Vendedor vendedorInstance = new Vendedor(id, legajo, nombre, apellido, dni);
                this.vendedor = vendedorInstance;
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void setLabels() {
        this.lblFecha.setText(this.factura.getFecha());
        this.lblVehiculo.setText(this.vehiculo.facturaStr());
        this.lblNombreCliente.setText(this.factura.getNombreCliente());
        this.lblApellidoCliente.setText(this.factura.getApellidoCliente());
        this.lblCluitCliente.setText(this.factura.getCuitcuilCliente());
        this.lblDireccionCliente.setText(this.factura.getDireccionCliente());
        this.lblDniCliente.setText(this.factura.getDniCliente());
        this.lblVendedor.setText(this.vendedor.facturaStr());
        this.lblMontoVenta.setText(this.factura.getMontoVenta().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        lblMontoVenta = new javax.swing.JLabel();
        lblDniCliente = new javax.swing.JLabel();
        lblDireccionCliente = new javax.swing.JLabel();
        lblCluitCliente = new javax.swing.JLabel();
        lblApellidoCliente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Liberation Serif", 1, 48)); // NOI18N
        jLabel2.setText("FACTURA");

        jLabel1.setText("Fecha:");

        jLabel3.setText("Vendedor:");

        jLabel4.setText("Vehiculo:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido:");

        jLabel7.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        jLabel7.setText("Facturación");

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 1, 28)); // NOI18N
        jLabel8.setText("Datos del Cliente");

        jLabel9.setText("Cuit/Cuil:");

        jLabel10.setText("Direccion:");

        jLabel11.setText("Dni:");

        jLabel12.setText("Monto:");

        lblNombreCliente.setText("jLabel13");

        lblFecha.setText("jLabel13");

        lblVendedor.setText("jLabel13");

        lblVehiculo.setText("jLabel13");

        lblMontoVenta.setText("jLabel13");

        lblDniCliente.setText("jLabel13");

        lblDireccionCliente.setText("jLabel13");

        lblCluitCliente.setText("jLabel13");

        lblApellidoCliente.setText("jLabel13");

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(283, 283, 283))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(266, 266, 266))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(330, 330, 330)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCluitCliente)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblDniCliente)
                            .addComponent(lblMontoVenta)
                            .addComponent(lblDireccionCliente)
                            .addComponent(lblVehiculo)
                            .addComponent(lblVendedor)
                            .addComponent(lblFecha)
                            .addComponent(lblApellidoCliente))
                        .addGap(442, 442, 442))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblVendedor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblVehiculo))
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNombreCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblApellidoCliente))
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblDireccionCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblCluitCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblDniCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblMontoVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu screenMenu = new Menu();
        screenMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblApellidoCliente;
    private javax.swing.JLabel lblCluitCliente;
    private javax.swing.JLabel lblDireccionCliente;
    private javax.swing.JLabel lblDniCliente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMontoVenta;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JLabel lblVendedor;
    // End of variables declaration//GEN-END:variables
}
